name: Expressions-Expansion
version: '${version}'
authors:
  - 4drian3d
  - Sliman4
main: me.sliman4.expressions.paper.PaperPlugin
description: Expressions Expansion for MiniPlaceholders
api-version: '1.19'
folia-supported: true
dependencies:
  - name: MiniPlaceholders
    required: true
